<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-LHVOOHO" failures="0" tests="5" name="numpyninja.Tests.ResisterTest" time="2.762" errors="1" timestamp="2022-09-27T14:20:28 EDT" skipped="4">
  <testcase classname="numpyninja.Tests.ResisterTest" name="setUp" time="2.760">
    <error message="Cannot invoke &quot;numpyninja.Pages.HomePage.registervalidation()&quot; because &quot;this.home&quot; is null" type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException: Cannot invoke "numpyninja.Pages.HomePage.registervalidation()" because "this.home" is null
at numpyninja.Tests.ResisterTest.setUp(ResisterTest.java:27)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:577)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:69)
at org.testng.internal.invokers.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:361)
at org.testng.internal.invokers.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:296)
at org.testng.internal.invokers.TestMethodWorker.invokeBeforeClassMethods(TestMethodWorker.java:180)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:122)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:806)
at org.testng.TestRunner.run(TestRunner.java:601)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:433)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:427)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:387)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- setUp -->
  <system-out/>
  <testcase classname="numpyninja.Tests.ResisterTest" name="RegisterWithEmptyField" time="0.000">
    <skipped/>
  </testcase> <!-- RegisterWithEmptyField -->
  <system-out/>
  <testcase classname="numpyninja.Tests.ResisterTest" name="EmptyPasswordTest" time="0.002">
    <skipped/>
  </testcase> <!-- EmptyPasswordTest -->
  <system-out/>
  <testcase classname="numpyninja.Tests.ResisterTest" name="EmptyConfirmPassword" time="0.000">
    <skipped/>
  </testcase> <!-- EmptyConfirmPassword -->
  <system-out/>
  <testcase classname="numpyninja.Tests.ResisterTest" name="DiffPassword" time="0.000">
    <skipped/>
  </testcase> <!-- DiffPassword -->
  <system-out/>
</testsuite> <!-- numpyninja.Tests.ResisterTest -->
